### ISSUE TITLE
Add fastRAG to our index of 'integrations'

### ISSUE THREAD

**Issue by TuanaCelik** [IntelLabs/fastRAG#13]
Hey maintainers. I'm trying to curate an index of Haystack integrations and projects (which for now I've simply named 'integrations'). These are custom nodes, document stores, pipelines and so on that can be used with Haystack, or built with Haystack. 
I've created a PR adding this repo to that index too: https://github.com/deepset-ai/haystack-integrations/pull/3 and was wondering if any of you would like to take a look and let me know if you're ok having this added there? The idea would be to render the markdown page somewhere on our website later.

**Comment by danielfleischer** [comment]
Thank you very much; we will be happy to be featured in your integrations/projects section. I had some additions to the description file.

**Comment by TuanaCelik** [comment]
Thanks @danielfleischer - I'll incorporate those into the file too 👍 Are you happy with people being forwarded to this issues page to report problems?

**Comment by danielfleischer** [comment]
Yes, that's fine.
