### ISSUE TITLE
Add updates to `PLAIDDocumentStore` 

### ISSUE THREAD

**Issue by jon-chuang** [IntelLabs/fastRAG#20]
See here: https://github.com/stanford-futuredata/ColBERT/issues/111, https://github.com/stanford-futuredata/ColBERT/blob/main/colbert/index_updater.py for the pathway

**Comment by danielfleischer** [comment]
Thanks for the feature request. We've added the new functionality in https://github.com/IntelLabs/fastRAG/blob/main/libs/colbert/colbert/index_updater.py. 

Currently it's not integrated into the `PLAIDDocumentStore` class. We're open for pull request on this, and any other topic! and we might add it ourselves in the coming weeks.
