### ISSUE TITLE
Document Lister not imported

### ISSUE THREAD

**Issue by karrtikiyer** [IntelLabs/fastRAG#24]
In GPT as both retriever and ranker, there is a line of code:
```
from fastrag.prompters.document_shapers.document_lister import DocumentLister
```
However if we look at `fastrag/prompters/document_shapers/__init__.py` the file is empty, the documentLister is not imported.

**Comment by danielfleischer** [comment]
`document_lister.py` is a file, treated as a module due to the existence of an empty `__init__.py` file. Can't reproduce as the class `DocumentLister` is imported correctly.
