### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by karrtikiyer-tw** [IntelLabs/fastRAG#27]
Wondering if this repo is being actively worked upon? Any future roadmap which can be shared with the community can be very helpful.
Thanks in advance,
Karrtik

**Comment by peteriz** [comment]
Hi @karrtikiyer-tw. Yes, new things are coming very soon 😎

**Comment by peteriz** [comment]
We don't anything like that publicly available.

**Comment by karrtikiyer-tw** [comment]
Ok I was wondering given the open source repo if some of us can contribute
by adding some features. Hence asked for it.

**Comment by peteriz** [comment]
Of course! Contributions are welcome. We are happy to discuss new additions/components that you would like to contribute.
