### ISSUE TITLE
How to use this repo on other languages?

### ISSUE THREAD

**Issue by Aysamu** [IntelLabs/fastRAG#28]
I want to use passages in different languages, is it possible?

**Comment by peteriz** [comment]
Hi @Aysamu sure. I would imagine that you can use a vector based index with the right model (in the language/languages you intend to use), along with a LLM that has multi-lingual capabilities.
In that case retrieval + generation pipelines should work without any issues.

**Comment by Aysamu** [comment]
> Hi @Aysamu sure. I would imagine that you can use a vector based index with the right model (in the language/languages you intend to use), along with a LLM that has multi-lingual capabilities. In that case retrieval + generation pipelines should work without any issues.

thank u!And I have another question, when I use ColBERTRanker as Reranker, it says 
`Exception: Exception while running node 'Reranker': 'list' object has no attribute 'cuda'
Enable debug logging to see the data that was passed when the pipeline failed.`

The Retriever is on gpu, and I also set Reranker on gpu, whats wrong?

**Comment by danielfleischer** [comment]
Can you share more details regarding how you use Colbert? what is the pipeline?

**Comment by Aysamu** [comment]
> Can you share more details regarding how you use Colbert? what is the pipeline?
I try the following code on jupyter
`from fastrag.stores import PLAIDDocumentStore
import fastrag, torch
from fastrag.retrievers.colbert import ColBERTRetriever
from fastrag.rankers.colbert import ColBERTRanker
from fastrag.kg_creators.luke import LukeKGCreator
from haystack import Pipeline

store = PLAIDDocumentStore(index_path="fastrag/downloads/Gone_with_the_wind_index",
                           checkpoint_path="fastrag/downloads/colbertv2.0",
                           collection_path="fastrag/downloads/Gone_with_the_wind.tsv")
retriever = ColBERTRetriever(store, top_k=20)
reranker = ColBERTRanker("fastrag/downloads/colbertv2.0", top_k=20)
kg_creator = LukeKGCreator(
    model_name="studio-ousia/luke-large-finetuned-tacred",
    use_gpu=True,
    batch_size=8,
    max_length=256,
    spacy_package="en_core_web_sm"
)`
p = Pipeline()
p.add_node(component=retriever, name="Retriever", inputs=["Query"])
p.add_node(component=reranker, name="Reranker", inputs=["Retriever"])
p.add_node(component=kg_creator, name="KGCreator", inputs=["Reranker"])
res = p.run(query="Who is SCARLETT O’HARA?")

**Comment by Aysamu** [comment]
> > Can you share more details regarding how you use Colbert? what is the pipeline?
>  I try the following code on jupyter
> ```
> from fastrag.stores import PLAIDDocumentStore
> import fastrag, torch
> from fastrag.retrievers.colbert import ColBERTRetriever
> from fastrag.rankers.colbert import ColBERTRanker
> from fastrag.kg_creators.luke import LukeKGCreator
> from haystack import Pipeline
> store = PLAIDDocumentStore(index_path="fastrag/downloads/Gone_with_the_wind_index",
>                            checkpoint_path="fastrag/downloads/colbertv2.0",
>                            collection_path="fastrag/downloads/Gone_with_the_wind.tsv")
> retriever = ColBERTRetriever(store, top_k=20)
> reranker = ColBERTRanker("fastrag/downloads/colbertv2.0", top_k=20)
> kg_creator = LukeKGCreator(
>     model_name="studio-ousia/luke-large-finetuned-tacred",
>     use_gpu=True,
>     batch_size=8,
>     max_length=256,
>     spacy_package="en_core_web_sm"
> )`
> p = Pipeline()
> p.add_node(component=retriever, name="Retriever", inputs=["Query"])
> p.add_node(component=reranker, name="Reranker", inputs=["Retriever"])
> p.add_node(component=kg_creator, name="KGCreator", inputs=["Reranker"])
> res = p.run(query="Who is SCARLETT O’HARA?")
> ```

**Comment by danielfleischer** [comment]
@Aysamu I'll have a look.

**Comment by danielfleischer** [comment]
I'm closing the issue as it's not related to non-English usage nor is new information provided regarding the ColBERT issue. If you want to continue it, open a dedicated issue and try to provide more context.
