### ISSUE TITLE
Multilingual RAG

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [IntelLabs/fastRAG#3]
Hi,

Thanks for this great repo!

Is there any way to use this pipeline in multilingual settings?

Are there multilingual version of Colbert, PLAID and FiD? Else, how would you recommend to proceed?

**Comment by peteriz** [comment]
Hi @Matthieu-Tinycoaching, the models can be used for fine-tuning (or pretraining) on any language you desire, with the right process, having enough data, etc. ColBERT and FiD are based on pre-trained BERT models (English) so both are inter-changeable with other LMs.

**Comment by Matthieu-Tinycoaching** [comment]
Hi @peteriz could you give me the name of the datasets used to fine-tune FiD and Colbert?

**Comment by peteriz** [comment]
Natural Questions.
