### ISSUE TITLE
Support for Haystack v2

### ISSUE THREAD

**Issue by filippo82** [IntelLabs/fastRAG#35]
Hi,

is there, in the roadmap, a plan to support/migrate to Haystack v2.0?

**Comment by danielfleischer** [comment]
Once the v2 version stabilizes and we see clearly what features are implemented and added, it'll be easier to make a decision.

**Comment by filippo82** [comment]
Thanks for the update 👍

**Comment by filippo82** [comment]
🥳 thanks for the new release!
