### ISSUE TITLE
Load performance: latency/RPS

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [IntelLabs/fastRAG#4]
Hi,

Have you load tested fastRAG pipeline with Colbert, PLAID and FiD on CPU instance?

Could you provide examples of latency, RPS relatively to CPU instance characteristics?

**Comment by danielfleischer** [comment]
We're currently working on these types of measurements. We'll publish some benchmarks in a blog, hopefully soon. Thanks for the question!

**Comment by danielfleischer** [comment]
I publish a [blog](https://medium.com/@daniel.fleischer/open-domain-q-a-using-dense-retrievers-in-fastrag-65f60e7e9d1e), benchmarking DPR and ColBERT+PLAID on CPU; have a look, you may find it interesting.
