### ISSUE TITLE
Confusions about REPLUG

### ISSUE THREAD

**Issue by richhh520** [IntelLabs/fastRAG#40]
1. How to train the retriever of REPLUG? How to update the embeddings of query and documents?
2. In your replug_parallel_reader.ipynb, why directly import the default BM25Retriever rather than the trained Retriever？
3. What does PromptModel do? What is its function? what does ReplugHFLocalInvocationLayer do? It seems this part is not mentioned in the paper.

Thanks for your help!

**Comment by kerkathy** [comment]
Thanks for the work, here also look forward to the implementation of the REPLUG training :)
