### ISSUE TITLE
State of Migration to Haystack 2.0

### ISSUE THREAD

**Issue by GHQB** [IntelLabs/fastRAG#49]
We are evaluating fastRAG for retrieval augmented generation.

A current showstopper is the dependency on the old Haystack library, is there a roadmap or an issue/epic one can follow to see the progress towards the goal mentioned in README.md, perhaps in a way an outsider can see where contributions might be welcome?

**Comment by danielfleischer** [comment]
We are working to bring compatibility with Haystack v2, as well as other new features; expect the update in the next few weeks.

**Comment by danielfleischer** [comment]
Enjoy the new release!
