### ISSUE TITLE
Question: What is the difference between fastRAG and Haystack?

### ISSUE THREAD

**Issue by HassamSheikh** [IntelLabs/fastRAG#56]
Hi,

Most of the code/components seems to be derived from Haystack so I was wondering, what exactly is the difference between this library and Haystack and in what cases I should use fastRAG over Haystack?

**Comment by danielfleischer** [comment]
fastRAG builds on top of Haystack, using its pipeline abstraction and being compatible with its components. We offer unique components and workflows that are optimized for Intel hardware, including examples and guides for optimization and quantization.
