### ISSUE TITLE
How would I go about getting many PDFs and DOCXs into a fastRAG instance?

### ISSUE THREAD

**Issue by CutNote** [IntelLabs/fastRAG#57]
Quick question:

I have a directory of directories of documents, some PDF, some DOCX. Is there some canonical, simple way to convert all these into the single .csv/.tsv file needed to get fastRAG going? Or, does everyone just have to whip up a custom python script to make that tsv alone? If so, what preprocessing makes fastRAG work most effectively? Also, if combining an LLM with a RAG system, as in the rag-prompt-hf example, would it be possible for the RAG application to be able to explicitly cite the document title? If so, would it need to be supplied in the .csv, or could it just be scraped in the content?

Thanks!

**Comment by erojaso** [comment]
I would like to suggest you

Tabular Data, RAG, & LLMs: Improve Results Through Data Table Prompting
https://medium.com/intel-tech/tabular-data-rag-llms-improve-results-through-data-table-prompting-bcb42678914b

Improve your Tabular Data Ingestion for RAG with Reranking
https://medium.com/intel-tech/improve-your-tabular-data-ingestion-for-rag-with-reranking-bebcf52cdde3

**Comment by CutNote** [comment]
Thanks! I'm quite new to NLP so this will be quite helpful. Take care!
