### ISSUE TITLE
issue while running client_inference_with_Llama_cpp.ipynb example!

### ISSUE THREAD

**Issue by abm1499** [IntelLabs/fastRAG#60]
I am trying to run example: client_inference_with_Llama_cpp.ipynb at Colab but I am facing an issue,

when I run from _haystack_integrations.components.generators.llama_cpp import LlamaCppGenerator_

I get following error in Colab.
![Screenshot 2024-08-31 at 14 26 26](https://github.com/user-attachments/assets/e7d73550-abb4-4cd3-8a67-f79b5c9e716c)

Please help!!!

**Comment by danielfleischer** [comment]
Need to install it using `pip install llama-cpp-haystack`, see https://github.com/deepset-ai/haystack-core-integrations/tree/main/integrations/llama_cpp.

**Comment by abm1499** [comment]
Thank you very much!
