### ISSUE TITLE
Ranker Score not updated in bi-encoder rankers

### ISSUE THREAD

**Issue by appoose** [IntelLabs/fastRAG#62]
In bi-encoder rankers, I noticed that the scores are not being attached to the documents. Is this intentional? Ideally, it would be more beneficial to populate the documents with their corresponding scores, allowing for downstream filtering.

```
        # Calculate similarity scores between query_document and documents_with_vectors
        doc_vectors = torch.tensor([doc.embedding for doc in documents_with_vectors])
        scores = torch.tensor(query_vector) @ doc_vectors.T  ## perhaps need to break it into chunks
        scores = scores.reshape(len(documents))
        indices = scores.cpu().sort(descending=True).indices
        return {"documents": [documents_with_vectors[i.item()] for i in indices[:top_k]]}
```

**Comment by danielfleischer** [comment]
Indeed, it could be beneficial having the scores for later processing. No plans on working on this right now but we are open for a PR 😄.

**Comment by appoose** [comment]
Please find the PR at https://github.com/IntelLabs/fastRAG/pull/63 . Please review.

**Comment by danielfleischer** [comment]
Merged. Thanks!
