### ISSUE TITLE
error when pip install fastrag in linux

### ISSUE THREAD

**Issue by fatpandaria** [IntelLabs/fastRAG#69]
ERROR: Cannot install fastrag==3.0.0 and opentelemetry-exporter-otlp-proto-grpc because these package versions have conflicting dependencies.

The conflict is caused by:
    fastrag 3.0.0 depends on protobuf==3.20.2
    opentelemetry-proto 1.28.0 depends on protobuf<6.0 and >=5.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

**Comment by danielfleischer** [comment]
Solved by #70.
